#coding=UTF-8

import os, sys, re



if len(sys.argv) < 3:
	print("Syntax is: python imgtohtml.py directory title")
	exit()
else:
	pass
	
bilder_path = os.getcwd() + '\\' + sys.argv[1] + '\\'
	
bild_lista = os.listdir(path=bilder_path)

print(bild_lista)

img_pattern = r'.jpg'
img_pattern2 = r'.JPG'
img_pattern3 = r'.PNG'
video_pattern = r'.mp4'


try:
	fil = open(r'C:\Users\maxextradata\Desktop\sites\idamax\bildsidor' + "\\" + sys.argv[1] + ".html", "a+")

	fil.write(r'''<!DOCTYPE html>

	<html>
		<head>
			<meta charset = "ansi">
			<title>Max & Ida</title>
			<link rel = "stylesheet" href="../css/normalize.css">
			<link href='https://fonts.googleapis.com/css?family=Changa+One|Open+Sans:400,400italic,700,700italic,800' rel='stylesheet' type='text/css'>
			<link rel = "stylesheet" href ="../css/main.css">
			<link rel ="stylesheet" href ="../css/responsive.css">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
		</head>
		<body>
			<header>
				<a href="../index.html" id = "logo">
					<h1>Max & Ida</h1>
					<h2>... i Sydamerika!</h2>
				</a>
				<nav>
					<ul>
						<li><a href="../index.html">Story</a></li>
						<li><a href="../bilder.html" class="selected">Bilder</a></li>
					</ul>
				</nav>
			</header>
			<div id="wrapper">
				<section>
					<h3>{}</h3>
					<ul id ="gallery">
					
					<!-- Generated by imgtohtml.py (by Max) -->
						'''.format(sys.argv[2]))

	for i in bild_lista:
		if re.search(img_pattern, i) or re.search(img_pattern2, i) or re.search(img_pattern3, i):
			fil.write(r'''
			<li>
				<a href="{}">
					<img src="{}" alt="" class = "bilder">
				</a>
			</li>'''.format(r'../img/' + sys.argv[1] + '\\' + str(i), r'../img/'+ sys.argv[1] + '\\' + str(i)))
		elif re.search(video_pattern, i):
			fil.write(r'''
			<li>
				<video controls>
					<source src="{}" type="video/mp4">
					Video not supported by browser or not uploaded yet to server!
				</video>
			</li>'''.format(r'../img/' + sys.argv[1] + '\\' + str(i)))
		else:
			fil.write('\n <!-- This was not recognized as image or video: ' + i + ' --> \n')
		
	fil.write(r'''
					<!-- Done -->
					</ul>
				</section>
				</div>
				<footer>
					<a href="https://www.facebook.com/max.korlinge">
						<img src="../img/fb.jpg" alt="Facebook icon" class = "social-icon">
					</a>
					<a href="https://www.twitter.com/maxkorlinge">
						<img src="../img/twitter.png" alt="Twitter icon" class= "social-icon">
					</a>
					<a href="http://www.threemuskytears.se">
						<img src="../img/musketeer.jpg" alt="ThreeMuskyTears icon" class="social-icon">
					</a>
					<p>&copy; 2016 Max Körlinge.</p>
				</footer>
		</body>
		</html>
		'''
	)

	fil.close()
	
	print('''
			.........
			Done!
			.........
			''')
	
except:
	print("Something went wrong trying to create or open the file!")
	
